### ISSUE TITLE
Problem with Cat Class

### ISSUE THREAD

**Issue by KobiShashs** [KobiShashs/Basic-HTML-CSS-JS#1]
var result  = (function Cat(name,age,color)
{
    this.name = name;
    this.age = age;
    this.color = color;
})();

**Comment by Alex-Golub** [comment]
Hi Kobi, I think I solved the problem

**Comment by KobiShashs** [comment]
@Alex-Golub Please share your code with me

**Comment by Alex-Golub** [comment]
`export function Cat(name, age, color) { // enable function export
    this.name = name;
    this.age = age;
    this.color = color;
};`

`import { Cat } from "./Cat.js";   // import Cat function from other JS file

let myCat = new Cat("aaa", 6, "Red");
console.log(myCat);
`

`<script type="module" src="site17.js"></script>  <!-- treat site17.js a module -->`

**Comment by KobiShashs** [comment]
@Alex-Golub You are the man!!!!
